# Fondation of Data Science



This notebook will just go through the basic topics in order:

* Data types
    * Numbers
    * Strings
    * Printing
    * Lists
    * Dictionaries
    * Booleans
    * Tuples 
    * Sets
* Comparison Operators
* if, elif, else Statements
* for Loops
* while Loops
* range()
* list comprehension
* functions
* lambda expressions
* map and filter
* methods
____

## Data types

### Numbers

In [6]:
1 + 2

2

In [7]:
1 * 3

3

In [8]:
1 / 2

0.5

In [9]:
2 ** 4

16

In [10]:
4 % 2

0

In [11]:
5 % 2

1

In [12]:
(2 + 3) * (5 + 5)

50

### Variable Assignment

In [13]:
# Can not start with number or special characters
name_of_var = 2

In [14]:
x = 2
y = 3

In [15]:
z = x + y

In [16]:
z

5

### Strings

In [17]:
'single quotes'

'single quotes'

In [18]:
"double quotes"

'double quotes'

In [19]:
" wrap lot's of other quotes"

" wrap lot's of other quotes"

### Printing

In [20]:
x = 'hello'

In [21]:
x

'hello'

In [22]:
print(x)

hello


In [23]:
num = 12
name = 'Sam'

In [24]:
print('My number is: {one}, and my name is: {two}'.format(one=num,two=name))

My number is: 12, and my name is: Sam


In [25]:
print('My number is: {}, and my name is: {}'.format(num,name))

My number is: 12, and my name is: Sam


### Lists

In [26]:
[1,2,3]

[1, 2, 3]

In [27]:
['hi',1,[1,2]]

['hi', 1, [1, 2]]

In [28]:
my_list = ['a','b','c']

In [29]:
my_list.append('d')

In [30]:
my_list

['a', 'b', 'c', 'd']

In [31]:
my_list[0]

'a'

In [32]:
my_list[1]

'b'

In [33]:
my_list[1:]

['b', 'c', 'd']

In [34]:
my_list[:1]

['a']

In [35]:
my_list[0] = 'NEW'

In [98]:
my_list

['NEW', 'b', 'c', 'd']

In [99]:
nest = [1,2,3,[4,5,['target']]]

In [100]:
nest[3]

[4, 5, ['target']]

In [101]:
nest[3][2]

['target']

In [102]:
nest[3][2][0]

'target'

### Dictionaries

In [37]:
d = {'key1':'item1','key2':'item2'}

In [38]:
d

{'key1': 'item1', 'key2': 'item2'}

In [39]:
d['key1']

'item1'

### Booleans

In [40]:
True

True

In [41]:
False

False

### Tuples 

In [1]:
t = ('a','b','c')

In [2]:
t[0]

'a'

In [4]:
t[0] = 'd'

TypeError: 'tuple' object does not support item assignment

### Sets

In [45]:
{1,2,3}

{1, 2, 3}

In [46]:
{1,2,3,1,2,1,2,3,3,3,3,2,2,2,1,1,2}

{1, 2, 3}

## Comparison Operators

In [47]:
1 > 2

False

In [48]:
1 < 2

True

In [49]:
1 >= 1

True

In [50]:
1 <= 4

True

In [51]:
1 == 1

True

In [52]:
'hi' == 'bye'

False

## Logic Operators

In [53]:
(1 > 2) and (2 < 3)

False

In [54]:
(1 > 2) or (2 < 3)

True

In [55]:
(1 == 2) or (2 == 3) or (4 == 4)

True

## if,elif, else Statements

In [56]:
if 0 < 1:
    print('Yes!')

Yep!


In [8]:
if 2 < 3:
    print('Yes!')

Yes!


In [6]:
if 10 < 11:
    print('Correct')
else:
    print('Incorrect')

Correct


In [9]:
if 1 > 2:
    print('Correct')
else:
    print('Incorrect')

Incorrect


In [60]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
else:
    print('Last')

middle


## for Loops

In [61]:
seq = [1,2,3,4,5,6,7,8,9,10]

In [26]:
for num in seq:
    print(num)

1
2
3
4
5
6
7
8
9


In [27]:
for num in seq:
    print('Hello')

Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello
Hello


In [28]:
for i in seq:
    print(i+i)

2
4
6
8
10
12
14
16
18


## while Loops

In [31]:
i = 0
while i < 5:
    print('i is: {}'.format(i))
    i = i+1
print('End of the loop {} i is not less than 5'.format(i))

i is: 0
i is: 1
i is: 2
i is: 3
i is: 4
End of the loop 5 i is not less than 5


## range()

In [66]:
range(5)

range(0, 5)

In [67]:
for i in range(5):
    print(i)

0
1
2
3
4


In [35]:
for i in range(1,11,2):
    print(i)
    

1
3
5
7
9


In [68]:
list(range(5))

[0, 1, 2, 3, 4]

## list comprehension

In [69]:
x = [1,2,3,4]

In [70]:
out = []
for item in x:
    out.append(item**2)
print(out)

[1, 4, 9, 16]


In [71]:
[item**2 for item in x]

[1, 4, 9, 16]

## functions

In [72]:
def my_func(param1='default'):
    """
    Docstring goes here.
    """
    print(param1)

In [73]:
my_func

<function __main__.my_func>

In [74]:
my_func()

default


In [75]:
my_func('new param')

new param


In [76]:
my_func(param1='new param')

new param


In [77]:
def square(x):
    return x**2

In [78]:
out = square(2)

In [79]:
print(out)

4


## lambda expressions

In [80]:
def times2(var):
    return var*2

In [81]:
times2(2)

4

In [23]:
seq = [1,2,3,4,5,6,7,8,9]
list([lambda var: var*2, seq])

[<function __main__.<lambda>(var)>, [1, 2, 3, 4, 5, 6, 7, 8, 9]]

In [20]:
print(l);

[<function <lambda> at 0x000001DD7F6278B0>, [1, 2, 3, 4, 5, 6, 7, 8, 9]]


In [25]:
Celcus = [48, 47,45, 36.5, 10, 5, 0] 
Farenheit = list(map(lambda x: (float(9)/5)*x + 32, Celcus))
print(Farenheit)

[118.4, 116.60000000000001, 113.0, 97.7, 50.0, 41.0, 32.0]


## map and filter

In [83]:
seq = [1,2,3,4,5]

In [84]:
map(times2,seq)

In [85]:
list(map(times2,seq))

[2, 4, 6, 8, 10]

In [86]:
list(map(lambda var: var*2,seq))

[2, 4, 6, 8, 10]

In [87]:
filter(lambda item: item%2 == 0,seq)

In [88]:
list(filter(lambda item: item%2 == 0,seq))

[2, 4]

## methods

In [111]:
st = 'hello my name is Sam'

In [112]:
st.lower()

'hello my name is sam'

In [113]:
st.upper()

'HELLO MY NAME IS SAM'

In [103]:
st.split()

['hello', 'my', 'name', 'is', 'Sam']

In [104]:
tweet = 'Go Sports! #Sports'

In [106]:
tweet.split('#')

['Go Sports! ', 'Sports']

In [107]:
tweet.split('#')[1]

'Sports'

In [92]:
d

{'key1': 'item1', 'key2': 'item2'}

In [93]:
d.keys()

dict_keys(['key2', 'key1'])

In [94]:
d.items()

dict_items([('key2', 'item2'), ('key1', 'item1')])

In [95]:
lst = [1,2,3]

In [96]:
lst.pop()

3

In [108]:
lst

[1, 2]

In [109]:
'x' in [1,2,3]

False

In [110]:
'x' in ['x','y','z']

True

# NumPy 

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

 Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [40]:
import numpy as np
my_list = [1,3,5,7]
my_list

[1, 3, 5, 7]

In [41]:
np.array(my_list)

array([1, 3, 5, 7])

In [42]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [43]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

# arange

Return evenly spaced values within a given interval.

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
even = np.arange(0,10,2)
even

array([0, 2, 4, 6, 8])

# Zeros and Ones

In [50]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [56]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [57]:
np.linspace(0,10,90)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [81]:
# import pandas as pd
import numpy.random as random

In [82]:
#np.linspace(0,10,900).reshape(30,30)

In [85]:
# df = pd.DataFrame(np.linspace(0,10,25).reshape(5,5), 
#                   index='A B C D E'.split(" "), 
#                   columns = 'Col1 Col2 Col3 Col4 Col5'.split(" "))

### eye
Creates an identity matirx

In [77]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [87]:
random.rand(10)

array([0.12862694, 0.72778575, 0.99004262, 0.08255034, 0.43368277,
       0.26412939, 0.12377231, 0.32860577, 0.69711601, 0.52559315])

In [88]:
random.rand(4,4)

array([[0.83967729, 0.09619474, 0.81137476, 0.51350488],
       [0.02350085, 0.57941278, 0.68017092, 0.98698605],
       [0.68982134, 0.82348341, 0.42336159, 0.3733852 ],
       [0.441933  , 0.71775761, 0.35601633, 0.84696347]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [80]:
random.randn(12)

array([ 0.6538844 ,  0.1863107 ,  0.52613258,  1.66481735,  0.32158831,
       -0.90792715,  0.20700823,  0.29624073,  0.12987136, -0.48080668,
       -0.67945242,  0.93680935])

In [89]:
random.randn(5,5)

array([[-0.11365247, -0.5399913 ,  0.61253959,  0.55778439,  0.5669064 ],
       [-0.14118477,  0.81214541,  0.0358557 ,  0.46836865, -0.30390999],
       [-1.51469165,  0.12023856,  0.56823896, -0.47160168, -0.51703586],
       [ 0.78122504,  1.26577415, -0.14813545, -0.99911705, -0.59444567],
       [-0.95075876,  1.47227997,  1.17736982, -1.23103174, -1.79050389]])

### randint return random integers


In [95]:
rand_int_array = np.random.randint(0,50,10)

In [96]:
rand_int_array

array([19, 32,  7, 23,  1, 13, 13,  0, 26, 25])

### dtype

You can also grab the data type of the object in the array:

In [97]:
rand_int_array.dtype

dtype('int32')

In [100]:
my_array = random.randint(0,10,15)

In [101]:
my_array

array([1, 3, 2, 0, 2, 1, 5, 9, 5, 0, 1, 5, 1, 0, 6])

In [102]:
my_array[0:5] = 2023
my_array

array([2023, 2023, 2023, 2023, 2023,    1,    5,    9,    5,    0,    1,
          5,    1,    0,    6])

In [104]:
my_copy  = my_array.copy()
my_copy

array([2023, 2023, 2023, 2023, 2023,    1,    5,    9,    5,    0,    1,
          5,    1,    0,    6])

# Introduction to Pandas

In this section of the course we will learn how to use pandas for data analysis. You can think of pandas as an extremely powerful version of Excel, with a lot more features. In this section of the course, you should go through the notebooks in this order:

* Introduction to Pandas
* DataFrames
* Missing Data
* GroupBy
* Merging,Joining,and Concatenating
* Operations
* Data Input and Output


# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [1]:
import pandas as pd
import numpy as np

In [2]:
from numpy.random import randn
np.random.seed(3)

In [23]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='X Y Z W'.split())

In [24]:
df

X         Y         Z         W
A -1.623285  0.646675 -0.356271 -1.743141
B -0.596650 -0.588594 -0.873882  0.029714
C -2.248258 -0.267762  1.013183  0.852798
D  1.108187  1.119391  1.487543 -1.118301
E  0.845833 -1.860890 -0.602885 -1.914472

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [25]:
df['Z']

A   -0.356271
B   -0.873882
C    1.013183
D    1.487543
E   -0.602885
Name: Z, dtype: float64

In [26]:
df[['X','W']]

X         W
A -1.623285 -1.743141
B -0.596650  0.029714
C -2.248258  0.852798
D  1.108187 -1.118301
E  0.845833 -1.914472

In [28]:
df.W

A   -1.743141
B    0.029714
C    0.852798
D   -1.118301
E   -1.914472
Name: W, dtype: float64

In [29]:
type(df.Z)

pandas.core.series.Series

In [30]:
df['New'] = df['X'] + df['Y']

In [31]:
df

X         Y         Z         W       New
A -1.623285  0.646675 -0.356271 -1.743141 -0.976610
B -0.596650 -0.588594 -0.873882  0.029714 -1.185244
C -2.248258 -0.267762  1.013183  0.852798 -2.516020
D  1.108187  1.119391  1.487543 -1.118301  2.227578
E  0.845833 -1.860890 -0.602885 -1.914472 -1.015056

In [32]:
df = df.drop('New', axis=1)

In [33]:
df

X         Y         Z         W
A -1.623285  0.646675 -0.356271 -1.743141
B -0.596650 -0.588594 -0.873882  0.029714
C -2.248258 -0.267762  1.013183  0.852798
D  1.108187  1.119391  1.487543 -1.118301
E  0.845833 -1.860890 -0.602885 -1.914472

In [34]:
df.drop('E', axis=0)

X         Y         Z         W
A -1.623285  0.646675 -0.356271 -1.743141
B -0.596650 -0.588594 -0.873882  0.029714
C -2.248258 -0.267762  1.013183  0.852798
D  1.108187  1.119391  1.487543 -1.118301

In [35]:
df

X         Y         Z         W
A -1.623285  0.646675 -0.356271 -1.743141
B -0.596650 -0.588594 -0.873882  0.029714
C -2.248258 -0.267762  1.013183  0.852798
D  1.108187  1.119391  1.487543 -1.118301
E  0.845833 -1.860890 -0.602885 -1.914472

### Selecting rows

In [36]:
df.loc['B']

X   -0.596650
Y   -0.588594
Z   -0.873882
W    0.029714
Name: B, dtype: float64

##### Or select based off of position instead of label

In [37]:
df.iloc[1]

X   -0.596650
Y   -0.588594
Z   -0.873882
W    0.029714
Name: B, dtype: float64

#### Selecting subset of rows and columns

In [38]:
df.loc['B','Y']

-0.5885943796882429

In [39]:
df.loc[['A','B'],['W','Y']]

W         Y
A -1.743141  0.646675
B  0.029714 -0.588594

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to 

In [ ]:
df>0

In [40]:
df[df>0]

X         Y         Z         W
A       NaN  0.646675       NaN       NaN
B       NaN       NaN       NaN  0.029714
C       NaN       NaN  1.013183  0.852798
D  1.108187  1.119391  1.487543       NaN
E  0.845833       NaN       NaN       NaN

In [42]:
df[df['Y']>0]['Y']

A    0.646675
D    1.119391
Name: Y, dtype: float64

In [43]:
df[df['W']>0][['Y','X']]

Y         X
B -0.588594 -0.596650
C -0.267762 -2.248258

For two conditions you can use | and & with parenthesis

In [44]:
df[(df['W']>0) & (df['Y'] > 1)]

Empty DataFrame
Columns: [X, Y, Z, W]
Index: []

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [45]:
# Reset to default 0,1...n index
df.reset_index()

index         X         Y         Z         W
0     A -1.623285  0.646675 -0.356271 -1.743141
1     B -0.596650 -0.588594 -0.873882  0.029714
2     C -2.248258 -0.267762  1.013183  0.852798
3     D  1.108187  1.119391  1.487543 -1.118301
4     E  0.845833 -1.860890 -0.602885 -1.914472

In [46]:
newind = 'CA NY WY OR CO'.split()

In [51]:
df['States'] = newind

In [52]:
df

X         Y         Z         W States
States                                               
CA     -1.623285  0.646675 -0.356271 -1.743141     CA
NY     -0.596650 -0.588594 -0.873882  0.029714     NY
WY     -2.248258 -0.267762  1.013183  0.852798     WY
OR      1.108187  1.119391  1.487543 -1.118301     OR
CO      0.845833 -1.860890 -0.602885 -1.914472     CO

In [53]:
df.set_index('States')

X         Y         Z         W
States                                        
CA     -1.623285  0.646675 -0.356271 -1.743141
NY     -0.596650 -0.588594 -0.873882  0.029714
WY     -2.248258 -0.267762  1.013183  0.852798
OR      1.108187  1.119391  1.487543 -1.118301
CO      0.845833 -1.860890 -0.602885 -1.914472

In [54]:
df

X         Y         Z         W States
States                                               
CA     -1.623285  0.646675 -0.356271 -1.743141     CA
NY     -0.596650 -0.588594 -0.873882  0.029714     NY
WY     -2.248258 -0.267762  1.013183  0.852798     WY
OR      1.108187  1.119391  1.487543 -1.118301     OR
CO      0.845833 -1.860890 -0.602885 -1.914472     CO

In [50]:
df.set_index('States',inplace=True)

In [55]:
df

X         Y         Z         W States
States                                               
CA     -1.623285  0.646675 -0.356271 -1.743141     CA
NY     -0.596650 -0.588594 -0.873882  0.029714     NY
WY     -2.248258 -0.267762  1.013183  0.852798     WY
OR      1.108187  1.119391  1.487543 -1.118301     OR
CO      0.845833 -1.860890 -0.602885 -1.914472     CO

Multi-Index and Index Hierarchy
Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [56]:
# Index Levels
outside = ['Citi','Citi','Citi','BOA','BOA','BOA']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [63]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['Open','Close'])
df

Open     Close
Citi 1  0.145063  1.167882
     2 -0.024104 -0.888657
     3 -2.915738 -0.971841
BOA  1 -0.591079 -0.516417
     2 -0.959996  0.377295
     3 -0.574708 -0.109454

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [64]:
df.loc['Citi']

Open     Close
1  0.145063  1.167882
2 -0.024104 -0.888657
3 -2.915738 -0.971841

In [65]:
df.loc['Citi'].loc[1]

Open     0.145063
Close    1.167882
Name: 1, dtype: float64

In [66]:
df.index.names

FrozenList([None, None])

In [70]:
df.index.names = ['Bank','Num']

In [71]:
df.index.names

FrozenList(['Bank', 'Num'])

In [72]:
df

Open     Close
Bank Num                    
Citi 1    0.145063  1.167882
     2   -0.024104 -0.888657
     3   -2.915738 -0.971841
BOA  1   -0.591079 -0.516417
     2   -0.959996  0.377295
     3   -0.574708 -0.109454

In [73]:
df.xs('Citi')

Open     Close
Num                    
1    0.145063  1.167882
2   -0.024104 -0.888657
3   -2.915738 -0.971841

In [74]:
df.xs(['Citi',1])

C:\Users\doumb\AppData\Local\Temp\ipykernel_14528\2456344931.py:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  df.xs(['Citi',1])


Open     0.145063
Close    1.167882
Name: (Citi, 1), dtype: float64

In [75]:
df.xs(1,level='Num')

Open     Close
Bank                    
Citi  0.145063  1.167882
BOA  -0.591079 -0.516417

# Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

In [79]:
df = pd.DataFrame(np.random.randint(-5,5,25).reshape(5,5),
                 index = 'A B C D E'.split(" "),
                  columns='X Y Z W V'.split(" "))
df.head()

X  Y  Z  W  V
A  2  0 -5 -2 -2
B  0  0 -1  2 -3
C -3  1  1 -2  1
D  2  2 -5  3  4
E -1  0 -1  0 -5

In [82]:
df[df> -3]

X  Y    Z  W    V
A  2.0  0  NaN -2 -2.0
B  0.0  0 -1.0  2  NaN
C  NaN  1  1.0 -2  1.0
D  2.0  2  NaN  3  4.0
E -1.0  0 -1.0  0  NaN

In [ ]:
# Vectorised functions
