# Fondation of Data Science



This notebook will just go through the basic topics in order:

* Data types
    * Numbers
    * Strings
    * Printing
    * Lists
    * Dictionaries
    * Booleans
    * Tuples 
    * Sets
* Comparison Operators
* if, elif, else Statements
* for Loops
* while Loops
* range()
* list comprehension
* functions
* lambda expressions
* map and filter
* methods
____

## Data types

### Numbers

In [5]:
!pwd

/c/Users/doumb/Desktop/VADSTI_2023/Refactored_Py_DS_ML_Bootcamp-master/01-Python-Crash-Course


In [6]:
1 + 2

2

In [7]:
1 * 3

3

In [8]:
1 / 2

0.5

In [9]:
2 ** 4

16

In [10]:
4 % 2

0

In [11]:
5 % 2

1

In [12]:
(2 + 3) * (5 + 5)

50

### Variable Assignment

In [13]:
# Can not start with number or special characters
name_of_var = 2

In [14]:
x = 2
y = 3

In [15]:
z = x + y

In [16]:
z

5

### Strings

In [17]:
'single quotes'

'single quotes'

In [18]:
"double quotes"

'double quotes'

In [19]:
" wrap lot's of other quotes"

" wrap lot's of other quotes"

### Printing

In [20]:
x = 'hello'

In [21]:
x

'hello'

In [22]:
print(x)

hello


In [23]:
num = 12
name = 'Sam'

In [24]:
print('My number is: {one}, and my name is: {two}'.format(one=num,two=name))

My number is: 12, and my name is: Sam


In [25]:
print('My number is: {}, and my name is: {}'.format(num,name))

My number is: 12, and my name is: Sam


### Lists

In [26]:
[1,2,3]

[1, 2, 3]

In [27]:
['hi',1,[1,2]]

['hi', 1, [1, 2]]

In [28]:
my_list = ['a','b','c']

In [29]:
my_list.append('d')

In [30]:
my_list

['a', 'b', 'c', 'd']

In [31]:
my_list[0]

'a'

In [32]:
my_list[1]

'b'

In [33]:
my_list[1:]

['b', 'c', 'd']

In [34]:
my_list[:1]

['a']

In [35]:
my_list[0] = 'NEW'

In [98]:
my_list

['NEW', 'b', 'c', 'd']

In [99]:
nest = [1,2,3,[4,5,['target']]]

In [100]:
nest[3]

[4, 5, ['target']]

In [101]:
nest[3][2]

['target']

In [102]:
nest[3][2][0]

'target'

### Dictionaries

In [37]:
d = {'key1':'item1','key2':'item2'}

In [38]:
d

{'key1': 'item1', 'key2': 'item2'}

In [39]:
d['key1']

'item1'

### Booleans

In [40]:
True

True

In [41]:
False

False

### Tuples 

In [1]:
t = ('a','b','c')

In [2]:
t[0]

'a'

In [4]:
t[0] = 'd'

TypeError: 'tuple' object does not support item assignment

### Sets

In [45]:
{1,2,3}

{1, 2, 3}

In [46]:
{1,2,3,1,2,1,2,3,3,3,3,2,2,2,1,1,2}

{1, 2, 3}

## Comparison Operators

In [47]:
1 > 2

False

In [48]:
1 < 2

True

In [49]:
1 >= 1

True

In [50]:
1 <= 4

True

In [51]:
1 == 1

True

In [52]:
'hi' == 'bye'

False

## Logic Operators

In [53]:
(1 > 2) and (2 < 3)

False

In [54]:
(1 > 2) or (2 < 3)

True

In [55]:
(1 == 2) or (2 == 3) or (4 == 4)

True

In [ ]:
# Part 3

## if,elif, else Statements

In [56]:
if 0 < 1:
    print('Yes!')

Yep!


In [8]:
if 2 < 3:
    print('Yes!')

Yes!


In [6]:
if 10 < 11:
    print('Correct')
else:
    print('Incorrect')

Correct


In [9]:
if 1 > 2:
    print('Correct')
else:
    print('Incorrect')

Incorrect


In [60]:
if 1 == 2:
    print('first')
elif 3 == 3:
    print('middle')
else:
    print('Last')

middle


In [8]:
score = 90
if score >= 90:
    print('A')
elif score >= 80:
    print('B')
elif score >= 70:
    print('C')
elif score >= 60:
    print('D')
else:
    print('F')

A


# FOUNDATION OF DATA SCIENCE DAY 2

## String is a collection of alphabets, words or other characters

## Integer is a whole number, positive or negative, without decimals, of unlimited length

## Lists are used to store multiple items in a single variable

### Dictionaries are Python's implementation of a data structure that is more generally known as an associative array. A dictionary consists of a collection of key-value pairs. Each key-value pair maps the key to its associated value

# Part 3
* for Loops
* while Loops
* range()
* list comprehension
* functions
* lambda expressions
* map and filter
* methods

## for Loops

In [13]:
seq = [1,2,3,4,5,6,7,8,9,10]
for num in seq:
    print(num**2)

1
4
9
16
25
36
49
64
81
100


In [10]:
for i in seq:
    print(i*2)

2
4
6
8
10


In [14]:
for num in seq:
    if num % 2 == 0:
        print(num)

2
4
6
8
10


In [15]:
st = 'I like apple, apple is good'

In [17]:
st.split()

['I', 'like', 'apple,', 'apple', 'is', 'good']

In [16]:
for char in st.split():
    print(char)

I
like
apple,
apple
is
good


## While loop

In [18]:
count = 0
while count < 6:
    print('Hello')
    count = count + 1

Hello
Hello
Hello
Hello
Hello
Hello


In [20]:
count = 0
while count <= 6:
    print(f'{count} is less than or equal 6!')
    count += 1

0 is less than or equal 6!
1 is less than or equal 6!
2 is less than or equal 6!
3 is less than or equal 6!
4 is less than or equal 6!
5 is less than or equal 6!
6 is less than or equal 6!


In [21]:
while False:
    print('Ok')

In [23]:
i  = 0
while i < 5:
    print('i is: {}'.format(i))
    i += 1
print('End of the loop {} because i is not less than 5'.format(i))

i is: 0
i is: 1
i is: 2
i is: 3
i is: 4
End of the loop 5 because i is not less than 5


## range()

In [26]:
list(range(11))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [28]:
list(range(1, 10,2))

[1, 3, 5, 7, 9]

In [30]:
for num in range(10):
    print(num**0.5)
    

0.0
1.0
1.4142135623730951
1.7320508075688772
2.0
2.23606797749979
2.449489742783178
2.6457513110645907
2.8284271247461903
3.0


### Want to create a list of even numbers betwee 0 and 50, using range method

In [33]:
even_list = list(range(0,50,2))
print(even_list)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]


## list comprehension

In [50]:
score = 60
if score >= 90:
    print('A')
elif score >= 80:
    print('B')
elif score >= 70:
    print('C')
elif score >= 60:
    print('D')
else:
    print('F')

D


In [48]:
score= 15

In [49]:
grade = [print('A') if score >= 90 else print('B')if score >= 80 
         else print('C') if score >= 70 else print('D') if score >= 60
         else print('F')
        ]

F


In [51]:
seq

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [53]:
a_list = []
for x in seq:
    if x % 2 == 0:
        a_list.append(x)
print(a_list)

[2, 4, 6, 8, 10]


In [58]:
even = [x for x in seq if  x % 2 == 0]
even

[2, 4, 6, 8, 10]

In [59]:
a_list = []
for x in seq:
    a_list.append(x**2)
print(a_list)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [61]:
square_list = [item**2 for item in seq]
square_list

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [75]:
students_gpa = {
    'John':[4.0,'US'],
    'Mya':[4.0,'US'],
    'Sean':[3.7,'US'],
    'Jon':[3.8,'INT'],
    'Sarah':[3.85,'INT'],
    'Isaac':[3.95,'INT'],
    'Issa':[2.8,'US']
}

In [76]:
for key, val in students_gpa.items():
    if (students_gpa[key][0]>3.8) and (students_gpa[key][1] == 'US'):
        print('The student named {}  is a US citizen and is qualified for the REU'.format(key))
    elif (students_gpa[key][0]>3.8) and (students_gpa[key][1] == 'INT'):
        print('{} is an excellent student, but not qualified the REU'.format(key))
    else:
        print('{} is not qualified for the REU'.format(key))

The student named John  is a US citizen and is qualified for the REU
The student named Mya  is a US citizen and is qualified for the REU
Sean is not qualified for the REU
Jon is not qualified for the REU
Sarah is an excellent student, but not qualified the REU
Isaac is an excellent student, but not qualified the REU
Issa is not qualified for the REU


In [71]:
students_gpa['John'][1]

'US'

In [65]:
l = [4.0, 'US']

In [67]:
l[1] == 'US'

'US'

In [63]:
students_gpa.items()

dict_items([('John', [4.0, 'US']), ('Mya', [4.0, 'US']), ('Sean', [3.7, 'US']), ('Jon', [3.8, 'INT']), ('Sarah', [3.85, 'INT']), ('Isaac', [3.5, 'INT']), ('Issa', [2.8, 'US'])])

## functions

### start def + the name of your function and end it with ":"
write the job of the function

In [77]:
def double_number(num):
    """
    THIS FUNCTION WILL RETURN THE DOUBLE OF THE NUMBER
    """
    return num*2

In [80]:
double_number(5)

10

In [82]:
def get_qualified_student(a_dict):
    for key, val in students_gpa.items():
        if (students_gpa[key][0]>3.8) and (students_gpa[key][1] == 'US'):
            print('The student named {}  is a US citizen and is qualified for the REU'.format(key))
        elif (students_gpa[key][0]>3.8) and (students_gpa[key][1] == 'INT'):
            print('{} is an excellent student, but not qualified the REU'.format(key))
        else:
            print('{} is not qualified for the REU'.format(key))

In [83]:
get_qualified_student(students_gpa)

The student named John  is a US citizen and is qualified for the REU
The student named Mya  is a US citizen and is qualified for the REU
Sean is not qualified for the REU
Jon is not qualified for the REU
Sarah is an excellent student, but not qualified the REU
Isaac is an excellent student, but not qualified the REU
Issa is not qualified for the REU


In [84]:
def print_name(name):
    print('Hi', name)

In [85]:
print_name('William')

Hi William


## lambda expressions

In [86]:
def double_number(num):
    return num*2

In [90]:
seq
l = lambda var: var*2

In [93]:

double_number(4)

8

###  We want to convert Celcus to Farenheit, using lambda expression

$F = \frac{9}{5}*C +32$

$[ 48,47,45,38,34,10,5,0]$

In [ ]:
Farenheit = []

## map and filter

In [97]:
seq

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [96]:
list(map(double_number,seq))

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [101]:
list(map(lambda var: var**2, seq))

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [103]:
list(filter(lambda var: var % 2 == 0, seq))

[2, 4, 6, 8, 10]

## methods

In [105]:
st = ' Hello $ my $ name $ is $ Shah'

In [107]:
st.split('$')

[' Hello my name is Shah']

In [108]:
my_email = 'mdoumbia@howard.edu'

In [110]:
my_email.split('@')[0]

'mdoumbia'

# Part 4: NumPy 

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.
Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](https://stackoverflow.com/questions/993984/what-are-the-advantages-of-numpy-over-regular-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

 Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [111]:
import numpy as np


In [113]:
b_list = [1,2,3,4,5,6]
c_list = [2,4,6,8,10]

In [114]:
b_list+c_list

[1, 2, 3, 4, 5, 6, 2, 4, 6, 8, 10]

In [119]:
b_list*3

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6]

In [117]:
my_array1 = np.array([1,2,3,4,5,6])
my_array2 = np.array([2,4,6,8,10,12])

In [118]:
my_array1+my_array2

array([ 3,  6,  9, 12, 15, 18])

In [120]:
my_array1*3

array([ 3,  6,  9, 12, 15, 18])

In [121]:
my_array2**0.5


array([1.41421356, 2.        , 2.44948974, 2.82842712, 3.16227766,
       3.46410162])

In [123]:
my_mat = np.array([[1,2,3],[5,6,4],[9,7,8]])
my_mat

array([[1, 2, 3],
       [5, 6, 4],
       [9, 7, 8]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

# arange

Return evenly spaced values within a given interval.

In [124]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
even = np.arange(0,10,2)
even

array([0, 2, 4, 6, 8])

# Zeros and Ones

In [131]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [132]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [139]:
L = np.linspace(0,120,25)
L

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105.,
       110., 115., 120.])

In [140]:
M = L.reshape(5,5)
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [81]:
# import pandas as pd
import numpy.random as random

In [82]:
#np.linspace(0,10,900).reshape(30,30)

# EYE

### Create identity matrix using eye

In [143]:
I3 = np.eye(3,3)
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [85]:
# df = pd.DataFrame(np.linspace(0,10,25).reshape(5,5), 
#                   index='A B C D E'.split(" "), 
#                   columns = 'Col1 Col2 Col3 Col4 Col5'.split(" "))

### eye
Creates an identity matirx

In [77]:
np.eye(4,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [147]:
import numpy.random as random
#import random

In [156]:
random.randint(0,50,10)

array([32, 48, 44,  1, 14, 49, 19,  4, 33, 27])

In [152]:
random.rand(4,4)

array([[0.75789484, 0.28609012, 0.52274721, 0.36588728],
       [0.46294657, 0.2261373 , 0.28155842, 0.23139162],
       [0.846066  , 0.56823862, 0.91641862, 0.5416709 ],
       [0.67845106, 0.16704904, 0.87415752, 0.32237198]])

### randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [153]:
random.randn(12)

array([-1.10775138,  0.27828048,  1.57669954,  0.85365531,  0.40621686,
        0.61083212,  0.77564004, -0.1004366 ,  0.39449772,  0.16975051,
       -0.01256042,  0.08302182])

In [154]:
random.randn(5,5)

array([[ 0.56430117, -0.51893563, -0.42197421, -0.67530494, -1.23099798],
       [ 0.51243953, -0.96104247, -1.1772777 , -0.58737178,  0.22621422],
       [ 1.61373717,  0.15879317,  1.74843579,  2.86104127,  0.73294784],
       [ 1.54031988,  0.7731716 ,  0.47136122, -1.28508832, -1.29096477],
       [-2.11414151,  0.36218829,  1.75019077,  0.6156631 , -0.82167517]])

### randint return random integers


In [95]:
rand_int_array = np.random.randint(0,50,10)

In [96]:
rand_int_array

array([19, 32,  7, 23,  1, 13, 13,  0, 26, 25])

In [102]:
my_array[0:5] = 2023
my_array

array([2023, 2023, 2023, 2023, 2023,    1,    5,    9,    5,    0,    1,
          5,    1,    0,    6])

In [104]:
my_copy  = my_array.copy()
my_copy

array([2023, 2023, 2023, 2023, 2023,    1,    5,    9,    5,    0,    1,
          5,    1,    0,    6])

# Part 5: Introduction to Pandas

In this section of the course we will learn how to use pandas for data analysis. You can think of pandas as an extremely powerful version of Excel, with a lot more features. In this section of the course, you should go through the notebooks in this order:

* Introduction to Pandas
* DataFrames
* Missing Data
* GroupBy
* Merging,Joining,and Concatenating
* Operations
* Data Input and Output


# DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [160]:
import pandas as pd
import numpy as np

In [161]:
from numpy.random import randn
np.random.seed(3)

In [162]:
'A B C D E'.split(" ")

['A', 'B', 'C', 'D', 'E']

In [175]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(" "),
                 columns = 'X Y Z W'.split(" "))
df.head()

X         Y         Z         W
A -1.623285  0.646675 -0.356271 -1.743141
B -0.596650 -0.588594 -0.873882  0.029714
C -2.248258 -0.267762  1.013183  0.852798
D  1.108187  1.119391  1.487543 -1.118301
E  0.845833 -1.860890 -0.602885 -1.914472

## Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [176]:
df['Z']

A   -0.356271
B   -0.873882
C    1.013183
D    1.487543
E   -0.602885
Name: Z, dtype: float64

In [177]:
df.Z

A   -0.356271
B   -0.873882
C    1.013183
D    1.487543
E   -0.602885
Name: Z, dtype: float64

In [178]:
df[['X','Z']]

X         Z
A -1.623285 -0.356271
B -0.596650 -0.873882
C -2.248258  1.013183
D  1.108187  1.487543
E  0.845833 -0.602885

In [179]:
df['new'] = df['Y']+df['W']
df.head()

X         Y         Z         W       new
A -1.623285  0.646675 -0.356271 -1.743141 -1.096466
B -0.596650 -0.588594 -0.873882  0.029714 -0.558881
C -2.248258 -0.267762  1.013183  0.852798  0.585036
D  1.108187  1.119391  1.487543 -1.118301  0.001090
E  0.845833 -1.860890 -0.602885 -1.914472 -3.775362

## Dropping column

In [180]:
df =df.drop('new', axis=1)

In [181]:
df.head(2)

X         Y         Z         W
A -1.623285  0.646675 -0.356271 -1.743141
B -0.596650 -0.588594 -0.873882  0.029714

### Dropping row

In [182]:
df = df.drop('E', axis=0)
df

X         Y         Z         W
A -1.623285  0.646675 -0.356271 -1.743141
B -0.596650 -0.588594 -0.873882  0.029714
C -2.248258 -0.267762  1.013183  0.852798
D  1.108187  1.119391  1.487543 -1.118301

### Selecting rows

In [184]:
df

X         Y         Z         W
A -1.623285  0.646675 -0.356271 -1.743141
B -0.596650 -0.588594 -0.873882  0.029714
C -2.248258 -0.267762  1.013183  0.852798
D  1.108187  1.119391  1.487543 -1.118301

In [183]:
df.loc['B']

X   -0.596650
Y   -0.588594
Z   -0.873882
W    0.029714
Name: B, dtype: float64

In [194]:
df.loc[['A','B'],['W','Y']]


W         Y
A -1.743141  0.646675
B  0.029714 -0.588594

##### Or select based off of position instead of label

In [192]:
df.iloc[1]['Y']

-0.5885943796882429

In [193]:
df.loc['B','Y']

-0.5885943796882429

#### Selecting subset of rows and columns

In [196]:
df.loc[['A','B'],['W','Y']]

W         Y
A -1.743141  0.646675
B  0.029714 -0.588594

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to 

In [197]:
df > -1

X     Y     Z      W
A  False  True  True  False
B   True  True  True   True
C  False  True  True   True
D   True  True  True  False

In [198]:
df[df > -1]

X         Y         Z         W
A       NaN  0.646675 -0.356271       NaN
B -0.596650 -0.588594 -0.873882  0.029714
C       NaN -0.267762  1.013183  0.852798
D  1.108187  1.119391  1.487543       NaN

In [205]:
df[df['W']>-1.65][['X','Z']]

X         Z
B -0.596650 -0.873882
C -2.248258  1.013183
D  1.108187  1.487543

For two conditions you can use | and & with parenthesis

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [206]:
df

X         Y         Z         W
A -1.623285  0.646675 -0.356271 -1.743141
B -0.596650 -0.588594 -0.873882  0.029714
C -2.248258 -0.267762  1.013183  0.852798
D  1.108187  1.119391  1.487543 -1.118301

In [207]:
df.reset_index()

index         X         Y         Z         W
0     A -1.623285  0.646675 -0.356271 -1.743141
1     B -0.596650 -0.588594 -0.873882  0.029714
2     C -2.248258 -0.267762  1.013183  0.852798
3     D  1.108187  1.119391  1.487543 -1.118301

In [208]:
newind = 'CA NY WY OR '.split()

In [209]:
df['States'] = newind

In [52]:
df

X         Y         Z         W States
States                                               
CA     -1.623285  0.646675 -0.356271 -1.743141     CA
NY     -0.596650 -0.588594 -0.873882  0.029714     NY
WY     -2.248258 -0.267762  1.013183  0.852798     WY
OR      1.108187  1.119391  1.487543 -1.118301     OR
CO      0.845833 -1.860890 -0.602885 -1.914472     CO

In [213]:
df = df.set_index('States')

In [214]:
df

X         Y         Z         W
States                                        
CA     -1.623285  0.646675 -0.356271 -1.743141
NY     -0.596650 -0.588594 -0.873882  0.029714
WY     -2.248258 -0.267762  1.013183  0.852798
OR      1.108187  1.119391  1.487543 -1.118301

In [50]:
#df.set_index('States',inplace=True)

Multi-Index and Index Hierarchy
Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [215]:
# Index Levels
outside = ['Citi','Citi','Citi','BOA','BOA','BOA']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [216]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['Open','Close'])
df

Open     Close
Citi 1  1.048148  1.333738
     2 -0.197415  1.774645
     3 -0.674728  0.150617
BOA  1  0.152946 -1.064195
     2  0.437947  1.938978
     3 -1.024931  0.899338

In [217]:
df.loc['Citi']

Open     Close
1  1.048148  1.333738
2 -0.197415  1.774645
3 -0.674728  0.150617

In [218]:
df.loc['Citi'].loc[1]

Open     1.048148
Close    1.333738
Name: 1, dtype: float64

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [64]:
df.loc['Citi']

Open     Close
1  0.145063  1.167882
2 -0.024104 -0.888657
3 -2.915738 -0.971841

In [224]:
df.loc['Citi'].loc[1]

Open     1.048148
Close    1.333738
Name: 1, dtype: float64

In [219]:
df.index.names

FrozenList([None, None])

In [220]:
df.index.names = ['Bank','Branch']

In [221]:
df.index.names

FrozenList(['Bank', 'Branch'])

In [225]:
df.xs(['Citi',1])

C:\Users\doumb\AppData\Local\Temp\ipykernel_5404\2456344931.py:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  df.xs(['Citi',1])


Open     1.048148
Close    1.333738
Name: (Citi, 1), dtype: float64

In [226]:
df.xs('Citi')

Open     Close
Branch                    
1       1.048148  1.333738
2      -0.197415  1.774645
3      -0.674728  0.150617

In [227]:
df.xs(1,level='Branch')

Open     Close
Bank                    
Citi  1.048148  1.333738
BOA   0.152946 -1.064195

# Missing Data

Let's show a few convenient methods to deal with Missing Data in pandas:

In [228]:
df = pd.DataFrame(np.random.randint(-5,5,25).reshape(5,5),
                 index = 'A B C D E'.split(" "),
                  columns='X Y Z W V'.split(" "))
df.head()

X  Y  Z  W  V
A -5  0  3 -1  3
B  3 -2 -1  4 -3
C  0 -1  2  4 -4
D  4 -5  2 -1  3
E  3 -1 -4 -1 -5

In [235]:
df = df[df> -3]
df

X    Y    Z  W    V
A  NaN  0.0  3.0 -1  3.0
B  3.0 -2.0 -1.0  4  NaN
C  0.0 -1.0  2.0  4  NaN
D  4.0  NaN  2.0 -1  3.0
E  3.0 -1.0  NaN -1  NaN

In [234]:
df.isna().sum()

X    1
Y    1
Z    1
W    0
V    3
dtype: int64

In [238]:
df.fillna(value = 0, inplace=True)

In [240]:
df[df>-1]

X    Y    Z    W    V
A  0.0  0.0  3.0  NaN  3.0
B  3.0  NaN  NaN  4.0  0.0
C  0.0  NaN  2.0  4.0  0.0
D  4.0  0.0  2.0  NaN  3.0
E  3.0  NaN  0.0  NaN  0.0

In [241]:
df = df.fillna(value = df['X'].mean())
df

X    Y    Z  W    V
A  0.0  0.0  3.0 -1  3.0
B  3.0 -2.0 -1.0  4  0.0
C  0.0 -1.0  2.0  4  0.0
D  4.0  0.0  2.0 -1  3.0
E  3.0 -1.0  0.0 -1  0.0

In [244]:
# Vectorised functions
df = df[df>1]

In [245]:
df.style.highlight_null(null_color="red")

In [246]:
df.style.background_gradient(cmap='Reds')

C:\Users\doumb\3D Objects\Python_new\lib\site-packages\pandas\io\formats\style.py:3555: RuntimeWarning: All-NaN slice encountered
  smin = np.nanmin(gmap) if vmin is None else vmin
C:\Users\doumb\3D Objects\Python_new\lib\site-packages\pandas\io\formats\style.py:3556: RuntimeWarning: All-NaN slice encountered
  smax = np.nanmax(gmap) if vmax is None else vmax


In [247]:
df.style.set_properties(**{'border': '3px dashed green',
                          'color': 'magenta'})

In [251]:
# df = pd.read_csv('Ecommerce.csv')
# df.head()